spring:
  datasource:
    url: jdbc:mysql://localhost:3306/livraria
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
#      # JPA OPTIONS:
#      # none         = ?
#      # update       = increment DB
#      # validate     = ?
#      # create-drop  = reset/create and drops DB when SeessionFactory closes
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

