CREATE TABLE IF NOT EXISTS Autor (
	id BIGINT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(150) NOT NULL,
	email VARCHAR(255) NOT NULL,
	data_nascimento DATE NOT NULL,
	mini_curriculo VARCHAR(255) NULL,
	PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Livro (
	id BIGINT NOT NULL AUTO_INCREMENT,
	titulo VARCHAR(255) NOT NULL,
	data_lancamento DATE NOT NULL,
	quantidade_paginas INT NOT NULL,
	id_autor BIGINT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (id_autor) REFERENCES Autor (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
) ENGINE = InnoDB;
